### Create User One
POST http://localhost:8080/eagle-bank/v1/users
Content-Type: application/json

{
  "name": "User One",
  "address": {
    "line1": "line11",
    "line2": "line12",
    "town": "town1",
    "county": "county1",
    "postcode": "postcode1"
  },
  "phoneNumber": "+1234567890",
  "email": "user.one1@example.com",
  "password": "qwerty!@£$%"
}


### Create User Two
POST http://localhost:8080/eagle-bank/v1/users
Content-Type: application/json

{
  "name": "User Two",
  "address": {
    "line1": "line21",
    "line2": "line22",
    "town": "town2",
    "county": "county2",
    "postcode": "postcode2"
  },
  "phoneNumber": "+234567890",
  "email": "user.two@example.com",
  "password": "qwerty!@£$%"
}


### Get user 1
GET http://localhost:8080/eagle-bank/v1/users/usr-useone1

### Get user 2
GET http://localhost:8080/eagle-bank/v1/users/usr-usetwo1

### Update user 1
PATCH http://localhost:8080/eagle-bank/v1/users/usr-useone1
Content-Type: application/json

{
  "address": {
    "postcode": "postcode111"
  },
  "phoneNumber": "0123456789"
}

### Update password user 2
PATCH http://localhost:8080/eagle-bank/v1/users/usr-usetwo1
Content-Type: application/json

{
  "password": "zxcvbnm!@£$%^&*()"
}


### Delete user
DELETE http://localhost:8080/eagle-bank/v1/users/usr-useone1
