### Create deposit transaction
POST http://localhost:8080/eagle-bank/v1/accounts/01195773/transactions
authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c3ItdXNlb25lMSIsImlhdCI6MTc1MzM0NjIwOCwiZXhwIjoxNzUzMzQ5ODA4LCJyb2xlIjoiQ1VTVE9NRVIiLCJuYW1lIjoidXNyLXVzZW9uZTEifQ.5P0md7z5RWBSda_e9_xcG6RiiZkXyXEKGjq9c2IfUju-9uGSM38Qay993_8U7Tu5
Content-Type: application/json

{
  "amount": 10.99,
  "currency": "GBP",
  "type": "deposit",
  "reference": "ref1"
}

### Create withdraw transaction
POST http://localhost:8080/eagle-bank/v1/accounts/01195773/transactions
authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c3ItdXNlb25lMSIsImlhdCI6MTc1MzM0NjIwOCwiZXhwIjoxNzUzMzQ5ODA4LCJyb2xlIjoiQ1VTVE9NRVIiLCJuYW1lIjoidXNyLXVzZW9uZTEifQ.5P0md7z5RWBSda_e9_xcG6RiiZkXyXEKGjq9c2IfUju-9uGSM38Qay993_8U7Tu5
Content-Type: application/json

{
  "amount": 5.99,
  "currency": "GBP",
  "type": "withdraw",
  "reference": "ref22"
}

### Get all transaction
GET http://localhost:8080/eagle-bank/v1/accounts/01195773/transactions
authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c3ItdXNlb25lMSIsImlhdCI6MTc1MzM0NjIwOCwiZXhwIjoxNzUzMzQ5ODA4LCJyb2xlIjoiQ1VTVE9NRVIiLCJuYW1lIjoidXNyLXVzZW9uZTEifQ.5P0md7z5RWBSda_e9_xcG6RiiZkXyXEKGjq9c2IfUju-9uGSM38Qay993_8U7Tu5

### Get 1 transaction
GET http://localhost:8080/eagle-bank/v1/accounts/01195773/transactions/tan-0a35079e
authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c3ItdXNlb25lMSIsImlhdCI6MTc1MzM0NjIwOCwiZXhwIjoxNzUzMzQ5ODA4LCJyb2xlIjoiQ1VTVE9NRVIiLCJuYW1lIjoidXNyLXVzZW9uZTEifQ.5P0md7z5RWBSda_e9_xcG6RiiZkXyXEKGjq9c2IfUju-9uGSM38Qay993_8U7Tu5
